server:
  port: 6666
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  config:
    activate:
      on-profile: dev